# Generated by Django 4.0.2 on 2022-02-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='format: Required, max-100', max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='format: required, letters, numbers, underscore, or hyphens', max_length=200, verbose_name='Category safe URL'),
        ),
    ]
